spring:
  application:
    name: staj

  datasource:
    url: jdbc:postgresql://localhost:5433/staj
    username: postgres
    password: 12345

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
